apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-cluster-essentials-bootstrap-sa
  namespace: tanzu-cluster-essentials-bootstrap
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tanzu-cluster-essentials-bootstrap-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tanzu-cluster-essentials-bootstrap-role-binding
subjects:
- kind: ServiceAccount
  name: tanzu-cluster-essentials-bootstrap-sa
  namespace: tanzu-cluster-essentials-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-cluster-essentials-bootstrap-role
